### ISSUE TITLE
Detection & tracking face

### ISSUE THREAD

**Issue by MyraBaba** [mrlathome/faceutils#2]
Hi,

when we are tracking the SAME face if people changed is the tracker still tracking face (different people)

How we can detect people and scene changed ? 

Best

**Comment by ahmdrz** [comment]
Hi
Every tracker has timeout ( default is 15 sec ). Dlib's tracker has good accuracy. So it has very low chance to lose face on tracking. After timeout ( At least one of trackers ) , program will re-recognize faces and start new tracker.

> How we can detect people and scene changed ?

Please explain more. I can't understand. You can find faces on `/ros_face_recognition/faces` service.

**Comment by MyraBaba** [comment]
Try to explain more : 

We are analysing the video streams and there is faces (ie talk show , advertisements etc). 

First detecting the faces and produce face features (faceID for recognizing).

And then we want to track these faces (same people) and let our program know these are the same people face from different angels. If the this people disappeared from the scene (scene changed or moved out of the camera vision etc)  than we detect faces and produce FaceID again for new person.

If we accurately track the same person with tracking (without trying to recognise) than we have very good amount of face pictures of the same person than we can utilise  in face features.

I hope I can make it more clear and explain myself more.

best

**Comment by ahmdrz** [comment]
Sorry for late answering.
Let me know , Do you want to use it in your physically robot ( same as us for athome robots ) ?

**Comment by MyraBaba** [comment]
We will use it for tv stream face tracking

**Comment by ahmdrz** [comment]
Do you want to use it on ROS ?
